[[main]]
  name = "Home"
  url = "/"
  weight = -110

[[main]]  
  name = "Videos"  
  url = "videos/"  
  weight = -109  

[[main]]
  name = "Feeds"
  url = "feeds/"
  weight = -108

[[main]]
  name = "About"
  url = "about/"
  weight = -107

[[main]]
  name = "Contribute"
  url = "contribute/"
  weight = -106

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/karlospn"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/carlosponsn/"

