name: Hugo CI site publish

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '.github/**'
      - 'data/**'
      - '.gitignore'
      - 'clean.py'
      - 'feeds.py'
      - 'news.py'
      - 'README.md'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true 
          fetch-depth: 1   

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        working-directory: ./site/dotnetramblings
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: karlospn/dotnetramblings-site-published-code
          publish_branch: main
          publish_dir: ./site/dotnetramblings/public
