name: Hugo CI site publish

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '.github/**'
      - 'data/**'
      - '.gitignore'
      - 'clean-news.py'
      - 'clean-videos.py'
      - 'common.py'
      - 'archive.py'
      - 'feeds.py'
      - 'migrate-content.py'
      - 'news.py'
      - 'README.md'
      - 'requirements.txt'
      - 'tests/**'
      - 'youtube.py'
  workflow_dispatch:

concurrency:
  group: site-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true 
          fetch-depth: 1   

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.131.0'
          extended: true

      - name: Build
        working-directory: ./site/dotnetramblings
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: karlospn/dotnetramblings-site-published-code
          publish_branch: main
          publish_dir: ./site/dotnetramblings/public
