name: Get and commit latest videos 
  
on:  
  schedule:  
    - cron:  '15 7 * * *'
  workflow_dispatch:
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
  
    - name: Set up Python  
      uses: actions/setup-python@v2  
      with:  
        python-version: '3.x'
  
    - name: Install dependencies  
      run: |  
        python -m pip install --upgrade pip  
        pip install -r requirements.txt   
  
    - name: Clean old videos 
      run: |  
        python clean-videos.py  

    - name: Get latest videos
      env:  
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}  
      run: |  
        python youtube.py  

    - name: Commit changes
      run: | 
        git config --local user.email "action@github.com"  
        git config --local user.name "GitHub Action"  
        git status
        git add .  
        git diff --quiet && git diff --staged --quiet || git commit -m "Automated script execution"  
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        branch: main
